services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    container_name: kaderblick-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: kaderblick
      MYSQL_USER: kaderblick
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-kaderblick}
    volumes:
      - kaderblick-db-data:/var/lib/mysql
    networks:
      db-net:
        aliases:
          - db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  kaderblick-db-data:
    external: true
    
networks:
  db-net:
    external: true
    name: kaderblick-net
