framework:
    messenger:
        failure_transport: failed
        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 2
                    max_delay: 60000
                options:
                    exchange:
                        name: kaderblick.commands
                        type: direct
                        default_publish_routing_key: async
                    queues:
                        kaderblick.async:
                            binding_keys: [async]
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: kaderblick.failed
                        type: direct
                        default_publish_routing_key: failed
                    queues:
                        kaderblick.failed:
                            binding_keys: [failed]

        routing:
            'App\Message\RecalcPlayerStatsMessage': async
            'App\Message\AwardTitlesMessage': async
            'App\Message\CheckCardThresholdsMessage': async
            'App\Message\ProcessPlayerDocumentMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
