<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Serves the public OG landing page for a shared poster.
 *
 * The page contains og:image / twitter:card meta tags so that WhatsApp,
 * Twitter, Facebook etc. show a proper image preview card instead of a
 * plain URL.
 */
class PosterSharePageController extends AbstractController
{
    /**
     * @param string $id filename without .png extension, e.g. "share_60b8c2a1f3c0d1.12345678"
     */
    #[Route('/poster-share/{id}', name: 'app_poster_share_page', methods: ['GET'])]
    public function sharePage(string $id): Response
    {
        // Only accept filenames generated by uniqid('share_', true).
        // Rejects path traversal, shell injection, wrong prefix, etc.
        if (!preg_match('/^share_[a-zA-Z0-9_.]+$/', $id)) {
            throw $this->createNotFoundException();
        }

        $filename = $id . '.png';
        $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/poster-share';

        if (!file_exists($uploadDir . '/' . $filename)) {
            throw $this->createNotFoundException('Poster nicht gefunden.');
        }

        $response = $this->render('poster_share/page.html.twig', [
            'id' => $id,
            'filename' => $filename,
        ]);

        // Public + cacheable so WhatsApp / Facebook / Twitter bots can scrape OG tags.
        // Cache-Control: private (Symfony default) would prevent social-media crawlers
        // from showing link preview cards.
        $response->setPublic();
        $response->setMaxAge(3600);

        return $response;
    }
}
